
on: pull_request

jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        id: version
        with:
          script: |
           const { body, base, created_at } = context.payload.pull_request
            return github.pulls.get({
            body,
            base : base.ref,
            created_at
            });

        
      - run: echo "${{ steps.pull_request_payload.outputs.result }}"
