
on: pull_request

jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        id: pull_request_payload
        with:
          result-encoding: "json"
          script: |
           const { body, base, created_at } = context.payload.pull_request 
           return { body: body, base : base.ref, created_at: created_at }
        

        
      - run: echo "${{ steps.pull_request_payload.outputs.result.base }}"
